### ISSUE TITLE
get_content() is called twice on every page load.

### ISSUE THREAD

**Issue by danmarsden** [mebis-lp/moodle-block_floatingbutton#1]
the get_content() function of a block is always called twice on a page load - for that reason we populate $this->content on the first call and then check it at the top and return the content if it isn't null - for an example see:
https://github.com/moodle/moodle/blob/master/blocks/html/block_html.php#L56

Please adjust your get_content function so that it performs a similar check and doesn't run the same set of functions/queries twice on the page load.

**Comment by sh-csg** [comment]
Thanks for raising this issue! 
I've built a similar check here: [https://github.com/mebis-lp/moodle-block_floatingbutton/blob/master/block_floatingbutton.php#L96]
get_content() always builds $this->content (once), but it always returns an empty dummy object. This is necessary as the floating button HTML code needs to reside outside the actual block area to avoid various problems. It is attached to the page header here: [https://github.com/mebis-lp/moodle-block_floatingbutton/blob/master/block_floatingbutton.php#L63]

**Comment by danmarsden** [comment]
haha - yeah - that was one of my canned responses - looking for specific code without looking closely at the function - of course that does the same thing there! :-)
