### ISSUE TITLE
styles.css could be more specific.

### ISSUE THREAD

**Issue by danmarsden** [mebis-lp/moodle-block_floatingbutton#2]
in your styles.css you define a number of generic styles that could potentially clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

in your case - the content is displayed within a block which will have the class .block_floatingbutton applied at the top of the block so you should be able to use things like this:
```
.block_floatingbutton .mbs-floatingicons {
```

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by sh-csg** [comment]
Thanks for raising this issue! #4 will change to more specific selectors.
